# Makefile for ECE-3056 Fall 2015
# Assignment-2
# Instructor: Sudhakar Yalamanchili 

CXX = /usr/bin/gcc
CXXFLAGS = -Wall -g 

EnergyModel: EnergyModel.o
	$(CXX) -g -o EnergyModel EnergyModel.o -lm

clean: 
	@rm *.o EnergyModel

